version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    restart: unless-stopped
